### ISSUE TITLE
Parallel table generator fails on Windows 10

### ISSUE THREAD

**Issue by cosinekitty** [cosinekitty/gearbox#20]
Apparently recursive directory deletion is more brittle on Windows 10 than Linux.

```
2021-01-13T03:14:12.80Z  [00]  Backprop[15]: white changes = 0, black changes = 0, total = 0, prev = 0
Unhandled exception. System.IO.IOException: The process cannot access the file 'b.index' because it is being used by another process.
   at System.IO.FileSystem.RemoveDirectoryRecursive(String fullPath, WIN32_FIND_DATA& findData, Boolean topLevel)
   at System.IO.FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
   at System.IO.Directory.Delete(String path, Boolean recursive)
   at EndgameTableGen.TableGenerator.GenerateTable(Int32[,] config) in c:\don\github\gearbox\src\EndgameTableGen\TableGenerator.cs:line 163
   at EndgameTableGen.ParallelTableGenerator.ThreadFunc(Object arg) in c:\don\github\gearbox\src\EndgameTableGen\ParallelTableGenerator.cs:line 159
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)
```

**Comment by cosinekitty** [comment]
I'm not going to use this algorithm anyway, so this bug is moot.
